# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.IntegerField()),
                ('similarity', models.CharField(max_length=20)),
                ('algorithm', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('start_date', models.DateTimeField(null=True, verbose_name='date started')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='date finished')),
                ('status', models.IntegerField()),
            ],
        ),
    ]
